sudo: require

services:
  - docker

before_install:
  - docker build -t dkvesic/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dkvesic/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-eu-north-1-769203255776"
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"